[package]
name = "shizuku"
version = "0.1.0"
authors = ["Amatsugu <khamraj@kaisei.app>"]
edition = "2024"

[dependencies]
client = { path = "../client", optional = true }
server = { path = "../server", optional = true }

[features]
default = ["client"]
server = ["dep:server"]
client = ["dep:client"]